apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zeno-project-external-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: zeno-project-secret
  data:
  - secretKey: REDIS__PASSWORD
    remoteRef:
      key: kv/prod/redis
      property: PASSWORD
  - secretKey: AUTH__CLIENT_SECRET
    remoteRef:
      key: kv/prod/project
      property: CLIENT_SECRET
  - secretKey: AUTH__SESSION_SECRET
    remoteRef:
      key: kv/prod/project
      property: SESSION_SECRET
  - secretKey: DATABASE__DB_USERNAME
    remoteRef:
      key: kv/prod/project
      property: DB_USERNAME
  - secretKey: DATABASE__DB_PASSWORD
    remoteRef:
      key: kv/prod/project
      property: DB_PASSWORD
  - secretKey: NOTIFICATIONS__MATRIX__USERNAME
    remoteRef:
      key: kv/matrix
      property: BOT_USERNAME
  - secretKey: NOTIFICATIONS__MATRIX__PASSWORD
    remoteRef:
      key: kv/matrix
      property: BOT_PASSWORD